[program:appjs]
process_name=%(program_name)s
command=/root/.nvm/versions/node/v18.15.0/bin/node /home/jsmcm/node_server/app.js
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
directory=/home/jsmcm/node_server
environment=HOME=/home/jsmcm/node_server
redirect_stderr=true
stdout_logfile=/home/jsmcm/node_server.log
stopwaitsecs=3600

